'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { HoloLabel } from '@/components/HoloText';
import { HoloPanel } from '@/components/HoloPanel';
import { PageContainer } from '@/components/Layout';
import { fadeInUp } from '@/lib/motion';
import styles from '../legal.module.css';

export default function TermsOfServicePage() {
    return (
        <PageContainer>
            {/* ─── Header ─── */}
            <motion.section
                className={styles.pageHeader}
                initial="hidden"
                animate="visible"
                variants={fadeInUp}
            >
                <HoloLabel>LEGAL</HoloLabel>
                <h1 className={styles.pageTitle}>Terms of Service</h1>
                <p className={styles.pageSubtitle}>
                    These terms govern your use of the W3B prediction fund platform and all related services.
                </p>
            </motion.section>

            {/* ─── Content ─── */}
            <div className={styles.content}>
                <Link href="/docs" className={styles.backLink}>← Back to Documentation</Link>
                <p className={styles.effectiveDate}>Effective Date: March 8, 2026</p>

                {/* §1 — Acceptance */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§1</span>
                    <h2 className={styles.sectionTitle}>Acceptance of Terms</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>
                                By accessing or using the W3B prediction fund platform, including the website (w3b.finance),
                                APIs, and any associated services (collectively, the &ldquo;Platform&rdquo;),
                                you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;).
                            </p>
                            <p>
                                If you do not agree to these Terms, you must not access or use the Platform.
                                Your continued use of the Platform constitutes ongoing acceptance of these Terms
                                and any future modifications.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §2 — Description of Services */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§2</span>
                    <h2 className={styles.sectionTitle}>Description of Services</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>
                                W3B is a quantitative prediction fund that generates returns through
                                CFTC-regulated event contracts. The Platform provides the following services:
                            </p>
                            <ul>
                                <li><strong>Fund Vault</strong> — invest capital and earn returns generated by quantitative probability models deployed into CFTC-regulated prediction markets.</li>
                                <li><strong>Performance Dashboard</strong> — view verified fund performance metrics, equity curve, and monthly returns with full transparency.</li>
                                <li><strong>Track Record</strong> — independently verified performance history through the Kalshi Exchange API.</li>
                                <li><strong>Account Management</strong> — register with your email, manage your fund position, and track your returns.</li>
                            </ul>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §3 — Eligibility */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§3</span>
                    <h2 className={styles.sectionTitle}>Eligibility</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>You represent and warrant that:</p>
                            <ul>
                                <li>You are at least 18 years of age (or the age of legal majority in your jurisdiction).</li>
                                <li>You are not a resident of, or located in, any jurisdiction subject to U.S. sanctions (including but not limited to Cuba, Iran, North Korea, Syria, and the Crimea, Donetsk, and Luhansk regions).</li>
                                <li>You are not on any U.S. or international sanctions list, including the OFAC Specially Designated Nationals list.</li>
                                <li>Your use of the Platform complies with all applicable laws and regulations in your jurisdiction.</li>
                                <li>You have the legal capacity to enter into these Terms and to use the Platform.</li>
                            </ul>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §4 — User Responsibilities */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§4</span>
                    <h2 className={styles.sectionTitle}>User Responsibilities</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>You are solely responsible for:</p>
                            <ul>
                                <li><strong>Account security.</strong> Safeguarding your login credentials and password. The Platform cannot recover lost credentials or reverse unauthorized transactions.</li>
                                <li><strong>Transaction accuracy.</strong> Verifying all transaction details before confirming. Fund transactions are processed according to the terms described herein.</li>
                                <li><strong>Regulatory compliance.</strong> Ensuring your use of the Platform complies with your local laws, including tax reporting obligations.</li>
                                <li><strong>Risk acknowledgment.</strong> Understanding and accepting the risks described in our <Link href="/legal/risk" className={styles.prose}>Risk Disclosures</Link>.</li>
                            </ul>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §5 — Fees */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§5</span>
                    <h2 className={styles.sectionTitle}>Fees</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>The Platform charges the following fees:</p>
                            <ul>
                                <li><strong>Management Fee:</strong> 0% per annum.</li>
                                <li><strong>Performance Fee:</strong> 20% of net profits, calculated against a high-water mark. No fee is charged during periods of loss.</li>
                                <li><strong>Deposit Fee:</strong> 0%.</li>
                                <li><strong>Withdrawal Fee:</strong> 0%.</li>
                            </ul>
                            <p>
                                Fee rates may be modified by the fund management team with advance notice to all participants.
                                All fee changes are communicated at least 30 days before taking effect.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §6 — Risk Acknowledgment */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§6</span>
                    <h2 className={styles.sectionTitle}>Risk Acknowledgment</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <div className={`${styles.highlightBox} ${styles.warningBox}`}>
                                <p>
                                    <strong>You acknowledge that using the Platform involves significant risk, including the potential
                                        loss of your entire deposited capital.</strong> Please read our comprehensive{' '}
                                    <Link href="/legal/risk">Risk Disclosures</Link> before using the Platform.
                                </p>
                            </div>
                            <p>
                                Past performance of the MONOLITH prediction engine or any individual strategy does not guarantee
                                future results. The Platform is provided &ldquo;as is&rdquo; without warranty of any kind.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §7 — Intellectual Property */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§7</span>
                    <h2 className={styles.sectionTitle}>Intellectual Property</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>
                                The W3B name, logo, and branding are proprietary. The MONOLITH prediction engine and its
                                strategies are proprietary and confidential.
                            </p>
                            <p>
                                The Platform&apos;s source code, trading strategies, probability models, and all related
                                intellectual property are owned by W3B. Unauthorized reproduction, distribution, or
                                reverse engineering is prohibited.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §8 — Limitation of Liability */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§8</span>
                    <h2 className={styles.sectionTitle}>Limitation of Liability</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>
                                To the maximum extent permitted by applicable law, W3B, its operators, contributors,
                                and affiliates shall not be liable for any indirect, incidental, special, consequential, or
                                punitive damages, including but not limited to loss of profits, data, or capital,
                                arising from your use of the Platform.
                            </p>
                            <p>
                                The Platform operates quantitative prediction models that execute positions on
                                CFTC-regulated exchanges. Trading outcomes are inherently uncertain and past
                                performance does not guarantee future results.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §9 — Termination & Suspension */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§9</span>
                    <h2 className={styles.sectionTitle}>Termination &amp; Suspension</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>
                                The Platform includes emergency controls that can be activated by the fund management team
                                in the event of extreme market conditions or a critical incident. Pausing the Platform temporarily
                                halts new positions to protect fund capital.
                            </p>
                            <p>
                                You may cease using the Platform at any time by withdrawing your funds.
                                There are no lock-up periods or withdrawal penalties under normal operating conditions.
                                Large withdrawals may be subject to a processing queue during periods of low liquidity.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §10 — Governing Law */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§10</span>
                    <h2 className={styles.sectionTitle}>Governing Law</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={styles.prose}>
                            <p>
                                These Terms shall be governed by and construed in accordance with the laws of the State of Florida,
                                United States of America, without regard to its conflict of law principles.
                            </p>
                            <p>
                                Any disputes arising from or related to these Terms or your use of the Platform shall be resolved
                                through binding arbitration in the State of Florida, in accordance with the rules of the
                                American Arbitration Association.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>

                <div className={styles.divider} />

                {/* §11 — Contact */}
                <motion.section className={styles.docSection} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={fadeInUp}>
                    <span className={styles.sectionNumber}>§11</span>
                    <h2 className={styles.sectionTitle}>Contact</h2>
                    <HoloPanel size="md" depth="mid">
                        <div className={`${styles.prose} ${styles.contactBlock}`}>
                            <p>
                                For questions about these Terms, contact us at{' '}
                                <a href="mailto:support@w3b.finance">support@w3b.finance</a>.
                            </p>
                        </div>
                    </HoloPanel>
                </motion.section>
            </div>
        </PageContainer>
    );
}
