// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title IYieldToken — Interface for yield-bearing tokens (stETH, etc.)
 */
interface IYieldToken is IERC20 {
    /// @notice Current value of shares in underlying terms
    function getShareValue(uint256 shares) external view returns (uint256);
}

/**
 * @title SelfRepayingVault — Alchemix-Style Auto-Repaying Loans
 * @notice Users deposit yield-bearing assets (e.g., stETH) and borrow up to
 *         50% of their deposit value. The yield generated by the deposited
 *         asset automatically repays the loan over time — no liquidation risk.
 *
 * How It Works:
 *   1. User deposits stETH (yield-bearing)
 *   2. User borrows USDC up to 50% of deposit value
 *   3. stETH earns yield (~3-5% APR from staking)
 *   4. Yield is periodically harvested and applied to repay the loan
 *   5. Once loan is fully repaid, user can withdraw full collateral
 *
 * Fees:
 *   - 10% of yield → protocol treasury
 *   - 90% of yield → auto-repayment of user's loan
 *
 * No Liquidation: Since borrow is capped at 50% and yield only grows,
 *                 the loan is always overcollateralized.
 */
contract SelfRepayingVault is Ownable, Pausable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    /* ============================================================ */
    /*                         CONSTANTS                            */
    /* ============================================================ */

    uint256 public constant PRECISION = 1e18;
    uint256 public constant BPS = 10_000;

    /// @notice Maximum LTV: 50%
    uint256 public constant MAX_LTV_BPS = 5000;

    /// @notice Protocol fee on yield: 10%
    uint256 public constant YIELD_FEE_BPS = 1000;

    /* ============================================================ */
    /*                          STRUCTS                             */
    /* ============================================================ */

    struct Position {
        uint256 depositAmount;      // Yield-bearing tokens deposited
        uint256 depositValue;       // USD value at deposit time (18 decimals)
        uint256 borrowAmount;       // USDC borrowed
        uint256 totalRepaid;        // Total yield applied as repayment
        uint256 lastHarvestTime;    // Last yield harvest timestamp
        bool active;                // Position is open
    }

    /* ============================================================ */
    /*                          STATE                               */
    /* ============================================================ */

    /// @notice The yield-bearing collateral (e.g., stETH)
    IYieldToken public immutable yieldToken;

    /// @notice The borrow asset (USDC)
    IERC20 public immutable borrowAsset;

    /// @notice Protocol treasury
    address public treasury;

    /// @notice Borrow asset price in 18 decimals (1 USDC = 1e18)
    uint256 public borrowAssetPrice;

    /// @notice Yield token price in 18 decimals
    uint256 public yieldTokenPrice;

    /// @notice Per-user positions
    mapping(address => Position) public positions;

    /// @notice Total deposits (in yield tokens)
    uint256 public totalDeposits;

    /// @notice Total active borrows (in borrow asset)
    uint256 public totalBorrows;

    /// @notice Total yield repaid across all users
    uint256 public totalYieldRepaid;

    /// @notice Total fees collected
    uint256 public totalFeesCollected;

    /* ============================================================ */
    /*                          EVENTS                              */
    /* ============================================================ */

    event Deposited(address indexed user, uint256 amount, uint256 value, uint256 timestamp);
    event Borrowed(address indexed user, uint256 amount, uint256 remainingCapacity, uint256 timestamp);
    event YieldHarvested(address indexed user, uint256 yieldAmount, uint256 repayment, uint256 fee, uint256 timestamp);
    event LoanFullyRepaid(address indexed user, uint256 totalRepaid, uint256 timestamp);
    event CollateralWithdrawn(address indexed user, uint256 amount, uint256 timestamp);
    event ManualRepay(address indexed user, uint256 amount, uint256 remaining, uint256 timestamp);

    /* ============================================================ */
    /*                       CONSTRUCTOR                            */
    /* ============================================================ */

    constructor(
        address _yieldToken,
        address _borrowAsset,
        address _treasury,
        uint256 _yieldTokenPrice,
        uint256 _borrowAssetPrice,
        address _owner
    ) Ownable(_owner) {
        require(_yieldToken != address(0), "SRV: zero yield token");
        require(_borrowAsset != address(0), "SRV: zero borrow asset");
        require(_treasury != address(0), "SRV: zero treasury");

        yieldToken = IYieldToken(_yieldToken);
        borrowAsset = IERC20(_borrowAsset);
        treasury = _treasury;
        yieldTokenPrice = _yieldTokenPrice;
        borrowAssetPrice = _borrowAssetPrice;
    }

    /* ============================================================ */
    /*                    CORE FUNCTIONS                            */
    /* ============================================================ */

    /**
     * @notice Deposit yield-bearing tokens as collateral
     * @param amount Amount of yield tokens to deposit
     */
    function deposit(uint256 amount) external nonReentrant whenNotPaused {
        require(amount > 0, "SRV: zero amount");

        IERC20(address(yieldToken)).safeTransferFrom(msg.sender, address(this), amount);

        Position storage pos = positions[msg.sender];
        uint256 value = (amount * yieldTokenPrice) / PRECISION;

        pos.depositAmount += amount;
        pos.depositValue += value;
        pos.active = true;
        if (pos.lastHarvestTime == 0) {
            pos.lastHarvestTime = block.timestamp;
        }

        totalDeposits += amount;

        emit Deposited(msg.sender, amount, value, block.timestamp);
    }

    /**
     * @notice Borrow against deposited yield-bearing collateral
     *         Max borrow = 50% of deposit value
     * @param amount Amount of borrow asset (USDC) to borrow
     */
    function borrow(uint256 amount) external nonReentrant whenNotPaused {
        require(amount > 0, "SRV: zero amount");
        Position storage pos = positions[msg.sender];
        require(pos.active, "SRV: no position");

        uint256 maxBorrowAmt = _maxBorrow(msg.sender);
        require(pos.borrowAmount + amount <= maxBorrowAmt, "SRV: exceeds max borrow");

        // Check vault has enough borrow asset
        uint256 available = borrowAsset.balanceOf(address(this));
        require(amount <= available, "SRV: insufficient liquidity");

        pos.borrowAmount += amount;
        totalBorrows += amount;

        borrowAsset.safeTransfer(msg.sender, amount);

        uint256 remaining = maxBorrowAmt - pos.borrowAmount;
        emit Borrowed(msg.sender, amount, remaining, block.timestamp);
    }

    /**
     * @notice Harvest yield from deposited tokens and auto-repay loan
     *         Anyone can call this to trigger repayment for any user.
     * @param user Address of the position to harvest
     */
    function harvestAndRepay(address user) external nonReentrant {
        Position storage pos = positions[user];
        require(pos.active, "SRV: no position");
        require(pos.borrowAmount > 0, "SRV: no loan");

        uint256 elapsed = block.timestamp - pos.lastHarvestTime;
        require(elapsed > 0, "SRV: already harvested");

        // Calculate yield: yield token value appreciation
        uint256 currentValue = (pos.depositAmount * yieldTokenPrice) / PRECISION;
        uint256 yieldGenerated = currentValue > pos.depositValue
            ? currentValue - pos.depositValue
            : 0;

        // Simulate time-based yield if price hasn't changed
        // (In production, this comes from actual staking yield)
        if (yieldGenerated == 0) {
            // Estimate: ~4% APR on deposit value
            yieldGenerated = (pos.depositValue * 400 * elapsed) / (BPS * 365 days);
        }

        if (yieldGenerated == 0) return;

        // Protocol fee: 10% of yield
        uint256 protocolFee = (yieldGenerated * YIELD_FEE_BPS) / BPS;
        uint256 repayment = yieldGenerated - protocolFee;

        // Cap repayment at outstanding borrow
        if (repayment > pos.borrowAmount) {
            repayment = pos.borrowAmount;
            protocolFee = (repayment * YIELD_FEE_BPS) / (BPS - YIELD_FEE_BPS);
        }

        // Apply repayment
        pos.borrowAmount -= repayment;
        pos.totalRepaid += repayment;
        pos.lastHarvestTime = block.timestamp;

        totalBorrows = totalBorrows > repayment ? totalBorrows - repayment : 0;
        totalYieldRepaid += repayment;
        totalFeesCollected += protocolFee;

        // Transfer fee to treasury (from vault's borrow asset balance)
        uint256 availableFee = borrowAsset.balanceOf(address(this));
        if (protocolFee > 0 && availableFee >= protocolFee) {
            borrowAsset.safeTransfer(treasury, protocolFee);
        }

        emit YieldHarvested(user, yieldGenerated, repayment, protocolFee, block.timestamp);

        // Check if loan is fully repaid
        if (pos.borrowAmount == 0) {
            emit LoanFullyRepaid(user, pos.totalRepaid, block.timestamp);
        }
    }

    /**
     * @notice Manually repay some or all of the loan
     * @param amount Amount to repay (use type(uint256).max for full)
     */
    function manualRepay(uint256 amount) external nonReentrant {
        Position storage pos = positions[msg.sender];
        require(pos.active, "SRV: no position");
        require(pos.borrowAmount > 0, "SRV: no loan");

        if (amount == type(uint256).max || amount > pos.borrowAmount) {
            amount = pos.borrowAmount;
        }

        borrowAsset.safeTransferFrom(msg.sender, address(this), amount);

        pos.borrowAmount -= amount;
        pos.totalRepaid += amount;
        totalBorrows = totalBorrows > amount ? totalBorrows - amount : 0;

        emit ManualRepay(msg.sender, amount, pos.borrowAmount, block.timestamp);

        if (pos.borrowAmount == 0) {
            emit LoanFullyRepaid(msg.sender, pos.totalRepaid, block.timestamp);
        }
    }

    /**
     * @notice Withdraw collateral (only when loan is fully repaid)
     * @param amount Amount of yield tokens to withdraw
     */
    function withdrawCollateral(uint256 amount) external nonReentrant {
        Position storage pos = positions[msg.sender];
        require(pos.active, "SRV: no position");

        if (pos.borrowAmount > 0) {
            // Can only withdraw excess above max borrow threshold
            uint256 currentMaxBorrow = _maxBorrow(msg.sender);
            // After withdrawal, remaining deposit must still cover borrow
            uint256 remainingValue = ((pos.depositAmount - amount) * yieldTokenPrice) / PRECISION;
            uint256 newMaxBorrow = (remainingValue * MAX_LTV_BPS) / BPS;
            require(pos.borrowAmount <= newMaxBorrow, "SRV: would undercollateralize");
        }

        require(amount <= pos.depositAmount, "SRV: insufficient collateral");

        pos.depositAmount -= amount;
        uint256 valueWithdrawn = (amount * yieldTokenPrice) / PRECISION;
        pos.depositValue = pos.depositValue > valueWithdrawn
            ? pos.depositValue - valueWithdrawn : 0;
        totalDeposits -= amount;

        if (pos.depositAmount == 0) {
            pos.active = false;
        }

        IERC20(address(yieldToken)).safeTransfer(msg.sender, amount);

        emit CollateralWithdrawn(msg.sender, amount, block.timestamp);
    }

    /* ============================================================ */
    /*                    VIEW FUNCTIONS                            */
    /* ============================================================ */

    /**
     * @notice Maximum borrow amount for a user
     */
    function maxBorrow(address user) external view returns (uint256) {
        return _maxBorrow(user);
    }

    /**
     * @notice Remaining borrow capacity
     */
    function remainingBorrowCapacity(address user) external view returns (uint256) {
        uint256 max = _maxBorrow(user);
        uint256 current = positions[user].borrowAmount;
        return max > current ? max - current : 0;
    }

    /**
     * @notice Estimated time to full repayment (in seconds)
     *         Based on current yield rate (~4% APR)
     */
    function estimatedRepaymentTime(address user) external view returns (uint256) {
        Position storage pos = positions[user];
        if (pos.borrowAmount == 0 || pos.depositValue == 0) return 0;

        // Annual yield after fee: deposit * 4% * 90% = deposit * 3.6%
        uint256 annualRepayment = (pos.depositValue * 360) / BPS; // 3.6%
        if (annualRepayment == 0) return type(uint256).max;

        return (pos.borrowAmount * 365 days) / annualRepayment;
    }

    /**
     * @notice Full position details
     */
    function getPosition(address user) external view returns (
        uint256 depositAmount,
        uint256 depositValue,
        uint256 borrowAmount,
        uint256 totalRepaid,
        uint256 maxBorrowAmount,
        uint256 remainingCapacity,
        uint256 estimatedTimeToRepay,
        bool active
    ) {
        Position storage pos = positions[user];
        depositAmount = pos.depositAmount;
        depositValue = pos.depositValue;
        borrowAmount = pos.borrowAmount;
        totalRepaid = pos.totalRepaid;
        maxBorrowAmount = _maxBorrow(user);
        remainingCapacity = maxBorrowAmount > borrowAmount ? maxBorrowAmount - borrowAmount : 0;
        estimatedTimeToRepay = this.estimatedRepaymentTime(user);
        active = pos.active;
    }

    /* ============================================================ */
    /*                    ADMIN                                     */
    /* ============================================================ */

    function setYieldTokenPrice(uint256 _price) external onlyOwner {
        yieldTokenPrice = _price;
    }

    function setBorrowAssetPrice(uint256 _price) external onlyOwner {
        borrowAssetPrice = _price;
    }

    function setTreasury(address _treasury) external onlyOwner {
        require(_treasury != address(0), "SRV: zero treasury");
        treasury = _treasury;
    }

    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }

    /**
     * @notice Fund vault with borrow asset (USDC) for lending
     */
    function fundVault(uint256 amount) external {
        borrowAsset.safeTransferFrom(msg.sender, address(this), amount);
    }

    /* ============================================================ */
    /*                    INTERNAL                                  */
    /* ============================================================ */

    function _maxBorrow(address user) internal view returns (uint256) {
        Position storage pos = positions[user];
        if (!pos.active || pos.depositAmount == 0) return 0;

        uint256 currentValue = (pos.depositAmount * yieldTokenPrice) / PRECISION;
        return (currentValue * MAX_LTV_BPS) / BPS;
    }
}
