#!/usr/bin/env python3
"""
MONOLITH RAG — Preloader

Runs at the START of every Antigravity conversation.
Generates a comprehensive context file covering the most critical
MONOLITH knowledge so the AI starts every conversation as a specialist.

This is the "always-on brain" — not topic-specific, but a broad
primer on the entire MONOLITH system state.
"""

import os
import sys
from pathlib import Path
from datetime import datetime

import chromadb
from sentence_transformers import SentenceTransformer

# --- Configuration ---
DB_DIR = os.path.join(os.path.dirname(__file__), 'vector_db')
COLLECTION_NAME = 'monolith_knowledge'
EMBED_MODEL = 'all-MiniLM-L6-v2'

BRAIN_DIR = os.path.expanduser('~/.gemini/antigravity/brain')

# Core knowledge domains to always preload
PRELOAD_QUERIES = [
    ("MONOLITH architecture and system design", 3),
    ("regime engine detection methods and current regime", 3),
    ("risk engine circuit breakers Critical 10 position sizing", 3),
    ("alpha engine signal pipeline 4-layer stack", 3),
    ("execution engine slippage implementation shortfall", 2),
    ("data pipeline validation failover reconciliation", 2),
    ("portfolio construction HRP Black-Litterman rebalancing", 2),
    ("MONOLITH expansion checklist current implementation status", 3),
    ("frontend holographic grid CRT terminal dashboard", 2),
    ("commodities gold bonds yield curve credit spreads", 2),
    ("crypto strategies funding rate liquidation cascade", 2),
    ("forex carry trade session breakout", 2),
    ("backtesting CPCV deflated Sharpe Monte Carlo", 2),
    ("free data sources connectors Alpaca OANDA Bybit", 2),
    ("build log checklist update protocol mandatory paired operation", 3),
    ("W3B frontend checklist framework tooling Web3 design system", 3),
]


def find_latest_brain_dir() -> str:
    """Find the most recent conversation's brain directory."""
    brain_path = Path(BRAIN_DIR)
    if not brain_path.exists():
        return None
    
    conv_dirs = [d for d in brain_path.iterdir() 
                 if d.is_dir() and not d.name.startswith('.')]
    
    if not conv_dirs:
        return None
    
    latest = max(conv_dirs, key=lambda d: d.stat().st_mtime)
    return str(latest)


def preload():
    """Run all preload queries and write comprehensive context."""
    
    # Load model and DB
    model = SentenceTransformer(EMBED_MODEL)
    client = chromadb.PersistentClient(path=DB_DIR)
    
    try:
        collection = client.get_collection(COLLECTION_NAME)
    except Exception:
        print("❌ No index found. Run 'python indexer.py' first.")
        sys.exit(1)
    
    total_chunks = collection.count()
    print(f"🧠 MONOLITH RAG Preloader — {total_chunks} chunks indexed")
    
    # Run all preload queries
    all_chunks = {}  # Deduplicate
    
    for query_text, n_results in PRELOAD_QUERIES:
        results = collection.query(
            query_texts=[query_text],
            n_results=n_results,
            include=['documents', 'metadatas', 'distances']
        )
        
        for doc, meta, dist in zip(
            results['documents'][0],
            results['metadatas'][0],
            results['distances'][0]
        ):
            chunk_id = f"{meta.get('source', '')}_{meta.get('chunk_index', 0)}"
            relevance = max(0, 1 - dist)
            
            if chunk_id not in all_chunks or all_chunks[chunk_id]['relevance'] < relevance:
                all_chunks[chunk_id] = {
                    'relevance': round(relevance, 3),
                    'source': meta.get('source', 'unknown'),
                    'section': meta.get('section', 'unknown'),
                    'content': doc
                }
    
    # Sort by source file then relevance
    sorted_chunks = sorted(all_chunks.values(), 
                          key=lambda x: (x['source'], -x['relevance']))
    
    print(f"📦 Retrieved {len(sorted_chunks)} unique chunks across {len(PRELOAD_QUERIES)} domains")
    
    # Write to brain directory
    brain_dir = find_latest_brain_dir()
    if not brain_dir:
        print("⚠️  No brain directory found — writing to current directory")
        brain_dir = os.path.dirname(__file__)
    
    context_file = os.path.join(brain_dir, 'monolith_rag_context.md')
    
    lines = [
        "# MONOLITH RAG — Preloaded Context",
        "",
        "> **This file was auto-generated by the MONOLITH RAG preloader.**",
        f"> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"> Source: {total_chunks} chunks from 59+ documents",
        f"> Loaded: {len(sorted_chunks)} most relevant chunks across {len(PRELOAD_QUERIES)} knowledge domains",
        "",
        "> Use this as your knowledge base. For deeper dives on specific topics,",
        "> run: `cd /Users/amiritate/EARN/W3B/monolith_rag && ./venv/bin/python query.py \"your topic\" --brain`",
        "",
        "---",
        "",
    ]
    
    current_source = None
    for chunk in sorted_chunks:
        if chunk['source'] != current_source:
            current_source = chunk['source']
            lines.extend([
                f"## 📄 {current_source}",
                "",
            ])
        
        lines.extend([
            f"### {chunk['section']}",
            f"*Relevance: {chunk['relevance']}*",
            "",
            chunk['content'],
            "",
            "---",
            "",
        ])
    
    with open(context_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"✅ Context written to: {context_file}")
    print(f"   File size: {os.path.getsize(context_file) / 1024:.1f} KB")


if __name__ == '__main__':
    preload()
