#!/usr/bin/env python3
"""
MONOLITH RAG — Query Engine

Searches the vector database for relevant context given a question,
and writes the results to the Antigravity brain directory.

Usage:
    python query.py "How does the gold-real rates model work?"
    python query.py "What circuit breakers does the risk engine have?" --top 15
    python query.py "Show me all USDA-related signals" --brain
"""

import os
import sys
import json
import argparse
from datetime import datetime
from pathlib import Path

import chromadb
from sentence_transformers import SentenceTransformer

# --- Configuration ---
DB_DIR = os.path.join(os.path.dirname(__file__), 'vector_db')
COLLECTION_NAME = 'monolith_knowledge'
EMBED_MODEL = 'all-MiniLM-L6-v2'

# Antigravity brain directory (where context gets injected)
BRAIN_DIR = os.path.expanduser(
    '~/.gemini/antigravity/brain'
)


def find_brain_dir() -> str:
    """Find the most recent conversation's brain directory."""
    brain_path = Path(BRAIN_DIR)
    if not brain_path.exists():
        return None
    
    # Find all conversation directories
    conv_dirs = [d for d in brain_path.iterdir() if d.is_dir() and not d.name.startswith('.')]
    
    if not conv_dirs:
        return None
    
    # Return the most recently modified one
    latest = max(conv_dirs, key=lambda d: d.stat().st_mtime)
    return str(latest)


def query_knowledge(question: str, top_k: int = 10, write_to_brain: bool = False):
    """Query the vector database and return relevant chunks."""
    
    # 1. Load model and DB
    model = SentenceTransformer(EMBED_MODEL)
    client = chromadb.PersistentClient(path=DB_DIR)
    
    try:
        collection = client.get_collection(COLLECTION_NAME)
    except Exception:
        print("❌ No index found. Run 'python indexer.py' first.")
        sys.exit(1)
    
    # 2. Query
    results = collection.query(
        query_texts=[question],
        n_results=top_k,
        include=['documents', 'metadatas', 'distances']
    )
    
    # 3. Format results
    formatted_chunks = []
    
    print(f"\n🔍 Query: \"{question}\"")
    print(f"📊 Found {len(results['documents'][0])} relevant chunks\n")
    print("=" * 70)
    
    for i, (doc, meta, dist) in enumerate(zip(
        results['documents'][0], 
        results['metadatas'][0],
        results['distances'][0]
    )):
        relevance = max(0, 1 - dist)  # Convert distance to relevance score
        source = meta.get('source', 'unknown')
        section = meta.get('section', 'unknown')
        
        print(f"\n--- Chunk {i+1} | Relevance: {relevance:.2f} | Source: {source} | Section: {section} ---")
        print(doc[:300] + "..." if len(doc) > 300 else doc)
        
        formatted_chunks.append({
            'rank': i + 1,
            'relevance': round(relevance, 3),
            'source': source,
            'section': section,
            'content': doc
        })
    
    print("\n" + "=" * 70)
    
    # 4. Write to brain directory if requested
    if write_to_brain:
        brain_dir = find_brain_dir()
        if brain_dir:
            context_file = os.path.join(brain_dir, 'monolith_rag_context.md')
            write_brain_context(context_file, question, formatted_chunks)
            print(f"\n✅ Context written to: {context_file}")
        else:
            print("\n⚠️  Could not find Antigravity brain directory")
    
    return formatted_chunks


def write_brain_context(filepath: str, question: str, chunks: list):
    """Write retrieved context to the Antigravity brain directory."""
    
    lines = [
        f"# MONOLITH RAG Context",
        f"",
        f"> Auto-generated by MONOLITH RAG system",
        f"> Query: \"{question}\"",
        f"> Retrieved: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"> Chunks: {len(chunks)}",
        f"",
        f"---",
        f"",
    ]
    
    for chunk in chunks:
        lines.extend([
            f"## [{chunk['rank']}] {chunk['source']} → {chunk['section']}",
            f"*Relevance: {chunk['relevance']}*",
            f"",
            chunk['content'],
            f"",
            f"---",
            f"",
        ])
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def multi_query(questions: list[str], top_k: int = 5):
    """Run multiple queries and combine results (for complex topics)."""
    
    model = SentenceTransformer(EMBED_MODEL)
    client = chromadb.PersistentClient(path=DB_DIR)
    collection = client.get_collection(COLLECTION_NAME)
    
    all_chunks = {}  # Deduplicate by chunk ID
    
    for question in questions:
        results = collection.query(
            query_texts=[question],
            n_results=top_k,
            include=['documents', 'metadatas', 'distances']
        )
        
        for doc, meta, dist in zip(
            results['documents'][0],
            results['metadatas'][0],
            results['distances'][0]
        ):
            chunk_id = f"{meta.get('source', '')}_{meta.get('chunk_index', 0)}"
            relevance = max(0, 1 - dist)
            
            if chunk_id not in all_chunks or all_chunks[chunk_id]['relevance'] < relevance:
                all_chunks[chunk_id] = {
                    'relevance': round(relevance, 3),
                    'source': meta.get('source', 'unknown'),
                    'section': meta.get('section', 'unknown'),
                    'content': doc
                }
    
    # Sort by relevance and return top results
    sorted_chunks = sorted(all_chunks.values(), key=lambda x: x['relevance'], reverse=True)
    return sorted_chunks[:top_k * 2]  # Return 2x for multi-query


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='MONOLITH RAG Query Engine')
    parser.add_argument('question', help='Question to search for')
    parser.add_argument('--top', type=int, default=10, 
                        help='Number of results to return (default: 10)')
    parser.add_argument('--brain', action='store_true',
                        help='Write results to Antigravity brain directory')
    args = parser.parse_args()
    
    query_knowledge(args.question, args.top, args.brain)
